### ISSUE TITLE
preauthorize doesn't default to expected values

### ISSUE THREAD

**Issue by lifeiscontent** [palkan/action_policy-graphql#13]
e.g.

I would expect `preauthorize: { raise: false, with: PostPolicy }` to default to `preauthorize: { to: :index?, raise: false, with: PostPolicy }` but it does not, in the README it states this is the expected behavior. So I guess this is a bug?

**Comment by palkan** [comment]
Default rule for `preauthorize` depends on the field type. From the readme:

> - for lists we use index?
> - for singleton fields we use show?

**Comment by lifeiscontent** [comment]
@palkan so in my case, this is a list. could it be because the options hash has `raise` in it?

**Comment by palkan** [comment]
No, it shouldn't.

Could you please show the GraphQL class?

**Comment by lifeiscontent** [comment]
@palkan sorry, it was because my type was not a list! My bad.
