### ISSUE TITLE
Does this work with GraphQL::Relay::Mutation's resolver?

### ISSUE THREAD

**Issue by juhaelee** [palkan/action_policy-graphql#15]
graphql-ruby's relay mutation resolver is a proc: (https://github.com/rmosolgo/graphql-ruby/blob/master/guides/relay/mutations.md). Is it possible to access the `authorize!` method there? What is the best way to utilize the authorize method? Currently, I am just accessing it as a class method and passing the context manually.

**Comment by palkan** [comment]
We do not support proc-based GraphQL Ruby API; so, the best way is to migrate to the [class-based  API](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/mutations/mutation_classes.md).
