### ISSUE TITLE
Best practice of record list / create permissions exposition and authorization

### ISSUE THREAD

**Issue by dmitry** [palkan/action_policy-graphql#4]
I like the idea behind the `expose_authorization_rules` macro. But it only works with existing records. What about if I have to check if there are a permission for the user to create a post? At the moment I'm using the following pattern:

user.rb
```ruby
module Types
  module Models
    class User < Types::Base::Object
      # ...
      field :can_create_post, Boolean, null: false
      def can_create_post
        allowed_to?(:create_post?, object)
      end
    end
  end
end

```

user_policy.rb
```ruby
class UserPolicy < ApplicationPolicy
  # actions with associations
  def create_post?
    policy_for(record: Post).create?
  end
end
```

post_policy.rb
```ruby
class PostPolicy < ApplicationPolicy
  def create?
    user.role.is_a?(Manager)
  end
end
```

post.rb (mutation)
```ruby
      def resolve(text:)
        authorize!(current_user || ::User, to: :create_post?)
```
I found it most simple, but seems like it might be improved.

**Comment by palkan** [comment]
What about the following:

```ruby
module Types
  module Models
    class User < Types::Base::Object
       expose_authorization_rules :create?, with: PostPolicy, field_name: :can_create_post
    end
  end
end
```
?

We can add a `field_name` option for more control.

**Comment by dmitry** [comment]
@palkan looks good to me.

What about the overall best practice for checking the permissions for the resource creation? Are you doing the same: `authorize!(::Post, to: :create?)` directly in the resolver / service object or is there are a better approach of doing checks?

**Comment by palkan** [comment]
>  for checking the permissions for the resource creation?

Yep, I'm using a similar approach: adding explicit `authorize!` calls to mutations.
In theory, it's possible to add `authorize: ...` modifier to mutation field; but that doesn't work for a single resource-related permissions, when you need to "load" the record first (`loads: ...` could only handle simple cases). Thus, you'll still need to use `authorize!` in the mutations's `resolve` method. For consistency, I prefer to use this explicit approach for all authorization checks.
