### ISSUE TITLE
Can ruby-next be a development-only dependency like action_policy?

### ISSUE THREAD

**Issue by haines** [palkan/action_policy-graphql#40]
I noticed in the latest update that action_policy-graphql is pulling ruby-next in as a dependency rather than just ruby-next-core.

Would it be possible to set this gem up to ship transpiled files in the gem (like action_policy itself) rather than requiring consumers of the gem to install ruby-next?

**Comment by palkan** [comment]
Yeah, that's a mistake, should be `ruby-next-core`. Will fix and release in the next patch version.

Thanks for reporting this 👍

**Comment by palkan** [comment]
Released in 0.5.2.
