### ISSUE TITLE
Issue with action policy 0.6.6: `undefined method 'relation_scope'`

### ISSUE THREAD

**Issue by olivierbuffon** [palkan/action_policy-graphql#48]
Since `action_policy` version have been bumped to `0.6.6` I go through the following error: `undefined method 'relation_scope'`.

### Tell us about your environment

**Ruby Version:**
3.2.2

**Framework Version (Rails, whatever):**
Rails 7.0

**Action Policy Version:**
0.6.6

**Action Policy GraphQL Version:**
0.5.3

### What did you do?
I simply updated `action_policy` from `0.6.5` to `0.6.6`

### What did you expect to happen?
Smooth update since it was a minor version bump.

### What actually happened?
It broke my development environment each time a policy class using relation_scope is called.

**Comment by palkan** [comment]
Sorry for that. Will take a look today.

**Comment by olivierbuffon** [comment]
@palkan Seems to be fixed in `0.6.7`. Thanks 🙏🏻
