### ISSUE TITLE
More releases or beta branch?

### ISSUE THREAD

**Issue by destructobeam** [palkan/action_policy-graphql#5]
Hey there,

Would it be possible to either push more releases to rubygems or make a separate beta branch for passing commits?

Would be good to be able to help test changes while not having to pull down breaking commits.

Cheers!

**Comment by palkan** [comment]
The latest RubyGems version (0.2.0) is up-to-date with the `master` branch.

> while not having to pull down breaking commits

Do you mean specific commits?

**Comment by destructobeam** [comment]
Ah okay, thanks, my bad. I just saw there was no tag  on here for `0.2.0` and assumed it hadn't made it to rubygems yet.

**Comment by palkan** [comment]
> there was no tag on here for 0.2.0

Oh, good catch! Forgot to push it to GitHub. Thanks!
