### ISSUE TITLE
Call the same policy multiple times

### ISSUE THREAD

**Issue by Tao-Galasse** [palkan/action_policy-graphql#53]
Hello @palkan ! 👋 

First of all, thank you for your amazing gem 💎 

Here is my issue: in my mutation, I want to run the same validation multiple times, because my record may have change.

To be more specific, I have a `Demand` object which has a `status`. I have an `AcceptDemand` mutation, which changes the status of the demand to the next one.
But, my users may have several roles, allowing them the accept multiple statuses at a time ; so I wrote something like this : 
```ruby
demand.status = demand.next_status
demand.status = demand.next_status while authorize! demand, to: :accept?
```
However, I realized we do not re-do the checks ; once the `authorize!` has been called, it is never called again, and returns the same result than the first time.
The issue is the same with `authorize!` or `allowed_to?` methods.

I understand it is probably a cache feature which makes sense in most cases, but could it be possible to force the `accept?` policy to be run again?

Thanks for your help & have a good day 😊

**Comment by palkan** [comment]
Hey,

Thanks for the details. That's an interesting use case.

To bust the cache, you can try providing a custom context to every authorize! call:

```ruby
demand.status = demand.next_status
iter = 0
loop do
  break if allowed_to?(:accept?, demand, context: {iter:})
  demand.status = demand.next_status
  iter += 1 
end
```

See it in action: https://runruby.dev/?gist=edddad2f3de94673cae7ca6254910ee7

**Comment by Tao-Galasse** [comment]
That's a good work around ! 😄 

Thanks a lot @palkan, I'll try this :) Nice idea! 💡
