### ISSUE TITLE
Authorize before fetching data

### ISSUE THREAD

**Issue by alexander37137** [palkan/action_policy-graphql#6]
Can i change authorize behavior to check policy before fetching data?

**Comment by palkan** [comment]
There is not short syntax for this right now (though we might consider adding this in the future releases).

For now you can do the following:

```ruby
field :something, SomeType

def something
  authorize! object, to: :rule?
  object.something
end
```

**Comment by alexander37137** [comment]
I see, thank you. I think for me it will be easier to make addition rest api for authorisation, than checking presence of current_user in every query. I think issue can be closed

**Comment by palkan** [comment]
@alexander37137 Please, take a look at the proposed API: #10 (also solves the problem of combining scoping and authorization).

**Comment by alexander37137** [comment]
Looks good to me
