### ISSUE TITLE
Using authorized_scope with authorize

### ISSUE THREAD

**Issue by alexander37137** [palkan/action_policy-graphql#8]
Why i cant use authorized_scope with authorize  in query type?

**Comment by palkan** [comment]
Right, currently, it's not possible to pass both options (we will revisit this behavior).

You can define `authorized_scope` in the field definition and do `authorize!` manually (as described here https://github.com/palkan/action_policy-graphql/issues/6#issuecomment-539081500).

**Comment by palkan** [comment]
Closing this in favor of #9
